### ISSUE TITLE
Style the thing

### ISSUE THREAD

**Issue by borna761** [borna761/BahaiEvents#14]

**Comment by wayferer** [comment]
- [ ] Header and Nav
- [ ] Content
- [ ] Timeline

**Comment by wayferer** [comment]
@borna761 I've finished the first pass of the styles. Thoughts?

**Comment by borna761** [comment]
Keep on doing what you're doing!

**Comment by wayferer** [comment]
just tweaked the events table a bit. thoughts?

**Comment by borna761** [comment]
I like the dates fit now. You don't want to make the table a bit wider? I think we can make the Event Group column a bit thinner too.

**Comment by wayferer** [comment]
ok trying something new. thoughts?

**Comment by borna761** [comment]
do you want to close this one?

**Comment by wayferer** [comment]
:smile:
