### ISSUE TITLE
Styling event table based on cycle

### ISSUE THREAD

**Issue by borna761** [borna761/BahaiEvents#21]
Added code for evenRow/oddRow, can you style it?

**Comment by wayferer** [comment]
thoughts?

**Comment by borna761** [comment]
Shift it so that the even rows are gray, and make it a bit lighter?

**Comment by wayferer** [comment]
I've lightened it a smidgen and they are already on the even cycles?

**Comment by borna761** [comment]
I meant on the odd ones... :-/

**Comment by wayferer** [comment]
how's that?

**Comment by borna761** [comment]
I'm tempted to go white for the odd-numbered cycles. really like the table size!

**Comment by wayferer** [comment]
now white :smile:

**Comment by borna761** [comment]
like it! center table or not?

**Comment by wayferer** [comment]
At the moment the table just expands out to 90% of the available width but wont go smaller than 850px. We could set a max-width of like 1200px and center it if you want?

**Comment by borna761** [comment]
that sounds good!

**Comment by wayferer** [comment]
Done

**Comment by borna761** [comment]
Pull request it :)
