### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by wayferer** [borna761/BahaiEvents#23]
- [x] Add ability to login
- [x] Should only be able to edit the event table when logged in

**Comment by wayferer** [comment]
@borna761 you want this yes?

**Comment by borna761** [comment]
yes please!

**Comment by wayferer** [comment]
ok so I have added the log in stuff following the guide here https://github.com/plataformatec/devise. its on the login branch and you will have to run 'bundle' and 'ran db:migrate' then go to '/admins/sign_up' to create a login for yourself. once we have it live and you have set up an account on the live server I'll push a change that will disable the ability to sign up on the live server because otherwise any one can make an account etc. i'm planning on doing this http://stackoverflow.com/a/8291318/780718.

**Comment by borna761** [comment]
I like!
